apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: buildah-build
spec:
  params:
    - name: image
      type: string
  workspaces:
    - name: source
  steps:
    - name: build-image
      image: quay.io/buildah/stable:v1.30
      securityContext:
        privileged: true
      workingDir: $(workspaces.source.path)
      script: |
        buildah bud -f Dockerfile -t $(params.image) .
        buildah push $(params.image)
