apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cicd-pipeline
spec:
  params:
    - name: git-url
      type: string
    - name: image
      type: string
    - name: sonar-url
      type: string
    - name: sonar-token
      type: string
  workspaces:
    - name: shared-workspace
    - name: maven-repo
    - name: gitops-repo
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: main
    - name: maven-build
      runAfter: [fetch-source]
      taskRef:
        name: maven-build
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-repo
          workspace: maven-repo
    - name: sonar-scan
      runAfter: [maven-build]
      taskRef:
        name: sonarqube-scan
      params:
        - name: sonar-url
          value: $(params.sonar-url)
        - name: sonar-token
          value: $(params.sonar-token)
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-image
      runAfter: [sonar-scan]
      taskRef:
        name: buildah-build
      params:
        - name: image
          value: $(params.image)
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: update-dev
      runAfter: [build-image]
      taskRef:
        name: update-deployment
      params:
        - name: image
          value: $(params.image)
        - name: overlay-dir
          value: overlays/dev
      workspaces:
        - name: gitops
          workspace: gitops-repo
    - name: update-uat
      runAfter: [update-dev]
      taskRef:
        name: update-deployment
      params:
        - name: image
          value: $(params.image)
        - name: overlay-dir
          value: overlays/uat
      workspaces:
        - name: gitops
          workspace: gitops-repo
    # Manual approval step for prod can be integrated via GitLab approvals or Tekton custom task
