apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: cicd-pipeline-template
spec:
  params:
    - name: git-url
    - name: image
    - name: sonar-url
    - name: sonar-token
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: cicd-pipeline-run-
      spec:
        pipelineRef:
          name: cicd-pipeline
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: image
            value: $(tt.params.image)
          - name: sonar-url
            value: $(tt.params.sonar-url)
          - name: sonar-token
            value: $(tt.params.sonar-token)
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: workspace-pvc
          - name: maven-repo
            persistentVolumeClaim:
              claimName: maven-repo-pvc
          - name: gitops-repo
            persistentVolumeClaim:
              claimName: gitops-repo-pvc
