apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  template:
    spec:
      containers:
        - name: petclinic
          image: image-registry.openshift-image-registry.svc:5000/dev/petclinic:latest
