apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: dev-
patches:
  - path: image-patch.yaml
images:
  - name: image-registry.openshift-image-registry.svc:5000/dev/petclinic
    newTag: latest
